### ISSUE TITLE
App crashes when setting wallpapaer

### ISSUE THREAD

**Issue by ronitkrshah** [trieulongben/react-native-wallpaper-manager#1]
My App working fine on A12+ devices. However when I tried on A10 & A8 my app crashes.

Is there any minimum requirements of android version to use this library?

**Comment by trieulongben** [comment]
Hi, it's require at least Android API level 24 which equivalent to Android 7.0 . I will try to reproduce your issue, thank you for reporting

**Comment by trieulongben** [comment]
@ronitkrshah  Hi i just added support from Android 7.0 version. Please check on lastest version 0.03

**Comment by ronitkrshah** [comment]
Thanks I will try this asap.
