### ISSUE TITLE
Android 12+ (Activity Restart)

### ISSUE THREAD

**Issue by helloukey** [trieulongben/react-native-wallpaper-manager#2]
After setting the wallpaper, I am noticing activity restart on Android 12 and above. Is there a fix to prevent it?

**Comment by trieulongben** [comment]
Hi helloukey, it's true that setting wallpaper will cause activity to restart. This behavior is Android system related, there isn't any solution for this now. Beside, i would suggest to save app's state before trigger wallpaper setting function then we restore later.

**Comment by helloukey** [comment]
@trieulongben Could you add a small section about it to your README markdown file?

**Comment by longgs25** [comment]
Sure, thank for your suggestion. I will update them on the weekend :D
